### ISSUE TITLE
Some files are missing.

### ISSUE THREAD

**Issue by SciFi1818** [jmendeth/quickvm#1]

**Comment by SciFi1818** [comment]
Some files are missing in it....please check

**Comment by mildsunrise** [comment]
Could you specify? What files are you talking about?

**Comment by SciFi1818** [comment]
The quickvm.QuickVM.*; package....you missed it , I think

**Comment by mildsunrise** [comment]
The source code is in the `src` folder, so the quickvm package is in [`src/quickvm`](https://github.com/jmendeth/quickvm/tree/master/src/quickvm) and the quickvm.QuickVM class is in [`src/quickvm/QuickVM.java`](https://github.com/jmendeth/quickvm/blob/master/src/quickvm/QuickVM.java), and so on (?)

**Comment by SciFi1818** [comment]
Oh...I missed that...!!

**Comment by SciFi1818** [comment]
Any way thanks for the support..

**Comment by mildsunrise** [comment]
No worries 😊
